import { ListView } from "std-widgets.slint";

export struct FolderItem {
    name : string,
    depth : int,
    is_folder : bool,
    is_expanded : bool
}

export component MainWindow inherits Window {
    width : 400px;
    height : 400px;
    title : "Torch Asset Manager";

    in property <[FolderItem]> folders;
    in property <int> selected_index;

    callback folder_clicked(index: int);
    
    ListView {
        for item[i] in folders : Rectangle {
            width : 100%;
            height : 30px;
            background : i == selected_index ? #4040a0 : transparent;

            HorizontalLayout {
                spacing : 8px;
                width : parent.width;
                height : parent.height;

                Rectangle {
                    width : item.depth * 16px;  // Identation space
                    height : 1px;
                    opacity : 0;
                }

                Text {
                    TouchArea {
                        width: parent.width;
                        height: parent.height;
                        clicked => { folder_clicked(i); }
                    }
                    text : item.is_folder ? "📁 " + item.name : "📄 " + item.name;
                    font-family : "monospace";
                    color : i == selected_index ? white : black;
                }
            }
        }
    }
}