import { ListView, ScrollView } from "std-widgets.slint";

export struct FolderItem {
    name : string,
    depth : int,
    is_folder : bool,
    is_expanded : bool,
    full_path : string
}

export component MainWindow inherits Window {
    width : 700px;
    height : 500px;
    title : "Torch Asset Manager";

    in property <[FolderItem]> folders;
    in property <int> selected_index;
    in property <string> preview_name;
    in property <string> preview_path;
    in property <string> preview_type;
    in property <string> preview_contents;

    callback folder_clicked(index: int);
    
    HorizontalLayout {
        spacing : 0px;

        // Left panel
        Rectangle {
            width : 300px;
            height : parent.height;

            ListView {
                for item[i] in folders : Rectangle {
                    width : 100%;
                    height : 30px;
                    background : i == selected_index ? #4040a0 : transparent;

                    HorizontalLayout {
                        spacing : 8px;
                        width : parent.width;
                        height : parent.height;

                        Rectangle {
                            width : item.depth * 16px;  // Identation space
                            height : 1px;
                            opacity : 0;
                        }

                        Text {
                            TouchArea {
                                width: parent.width;
                                height: parent.height;
                                clicked => { folder_clicked(i); }
                            }
                            text : item.is_folder ? "📁 " + item.name : "📄 " + item.name;
                            font-family : "monospace";
                            color : i == selected_index ? white : black;
                        }
                    }
                }
            }
        }

        // Middle spacing
        Rectangle {
            width : 1px;
            height : parent.height;
            background : #888;
        }

        // Right panel
        Rectangle {
            height : parent.height;
            padding : 16px;
            background : #f0f0f0;

            VerticalLayout {
                spacing : 0px;

                Text {
                    height : 30px;
                    text : "Selected item";
                    font-size: 18px;
                    font-weight: 500;
                }

                Text {
                    height : 20px;
                    text : "Name:" + preview_name;
                }

                Text {
                    height : 20px;
                    text : "Path: " + preview_path;
                    wrap : word-wrap;
                }

                Text {
                    height : 20px;
                    text: "Type: " + preview_type;
                }

                // Placeholder for image/text previews later
                Rectangle {
                    height : 400px;
                    background : #edd;
                    border-radius:  4px;

                    // Text {
                    //     text: "Preview content here...";
                    //     vertical-alignment: center;
                    //     horizontal-alignment: center;
                    //     color: #666;

                    //     width : parent.width;
                    //     height : parent.height;
                    // }

                    Text {
                        text : preview_contents;
                        wrap : word-wrap;
                        font-size: 14px;
                        font-family: "monospace";
                        width : parent.width;
                    }
                }
            }
        }
    }
}